# Generated by Django 5.2.7 on 2025-10-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_message',
            new_name='ContactMessage',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
